name: Python Script with OpenAI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Run Python Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY2 }}
        run: python morgenpodcast.py
      
      - name: Commit generated MP3
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.mp3
          git commit -m "Add generated MP3 file" || exit 0
          git push
