name: Python Script with OpenAI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # <-- Das ist entscheidend für Push-Berechtigung

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python morgenpodcast.py

      - name: Commit generated MP3
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.mp3
          git commit -m "Add generated MP3 file" || echo "No changes to commit"
          git push
